In [1]:
import numpy as np

# Matriks yang ingin diinvers
matriks = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 10]])

# Menghitung determinan matriks
determinan = np.linalg.det(matriks)

# Cek apakah determinan tidak sama dengan nol
if determinan != 0:
    # Menghitung invers matriks
    invers_matriks = np.linalg.inv(matriks)
    
    print("Matriks Awal:")
    print(matriks)
    print("\nInvers Matriks:")
    print(invers_matriks)
else:
    print("Determinan matriks sama dengan nol, tidak bisa diinvers.")

Matriks Awal:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Invers Matriks:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
